### PR TITLE
github action: updated os-version to ubuntu-22.04

### PR DESCRIPTION
**Pull request by JanStaschulat**

### CODE REVIEW

**Review by pablogs9 — APPROVED** [review]

**Comment by JanStaschulat** [comment]
@mergify backport master

**Comment by pablogs9** [comment]
@JanStaschulat This mergify error should be fixed by `ros2` organization owners, right?

**Comment by JanStaschulat** [comment]
@pablogs9 . Yes. I posted this error in the mergify-chat: The response was to contact ros2 maintainers. I'll do that. 
grafik

grafik

**Comment by JanStaschulat** [comment]
@clalancette could you update these mergify permissions on ros2/rclc repo?

**Comment by JanStaschulat** [comment]
@mergify backport master

**Comment by JanStaschulat** [comment]
> > @clalancette could you update these mergify permissions on ros2/rclc repo?
> 
> I've updated the permissions now. Give it a try again.

Thanks a lot @clalancette, mergify works again. CC @pablogs9

**Pull request merged**
