### PR TITLE
Add QoS entity creation API

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Review by JanStaschulat — APPROVED** [review]

**Comment by pablogs9** [comment]
@backport galactic foxy

**Comment by pablogs9** [comment]
@mergify backport galactic foxy

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/timeout-rmw-qos-in-rclc-apis/21784/1

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-embedded-wg-meetings/15460/22

**Pull request merged**
