### PR TITLE
Fix action client & server deallocation

### PR DESCRIPTION
**Pull request by pablogs9**
This PR ensures the cleaning of deallocated sections

### CODE REVIEW

**Comment by pablogs9** [comment]
Today's CI is passing, are we ok with that? @JanStaschulat @Acuadros95 can we assume that this is a CI or Action failure?

**Review by JanStaschulat — APPROVED** [review]
LGTM

**Comment by JanStaschulat** [comment]
> Today's CI is passing, are we ok with that? @JanStaschulat @Acuadros95 can we assume that this is a CI or Action failure?

Let's see if the scheduled CI job tomorrow builds successfully.

**Comment by pablogs9** [comment]
Everything ok today: https://github.com/ros2/rclc/actions/runs/1932317583

**Review by JanStaschulat — APPROVED** [review]

**Comment by JanStaschulat** [comment]
LGTM

**Review by Acuadros95 — APPROVED** [review]

**Pull request merged**
