### PR TITLE
Feature/windows port

### PR DESCRIPTION
**Pull request by JanStaschulat**
@ralph-lange, @pablogs9, @norro , @Karsten1987 

This pull request contains the changes for compiling ros2/rclc on Windows platform (with Foxy Release):

**Tests:**
- unit tests for rclc and rclc_lifecycle passed successfully
- test programs in rclc_examples run successfully

**Compiled and build locally on**
- Windows with Foxy 
- Linux with Dashing
- Linux with Foxy

### CODE REVIEW

**Comment by pablogs9** [comment]
Let's check if micro-ROS CI pass: https://github.com/micro-ROS/micro_ros_setup/pull/294

**Comment by pablogs9** [comment]
micro-ROS build system likes your changes

**Comment by JanStaschulat** [comment]
@pablogs9 thanks for checking on micro-ros. The install of include was missing: [commit](https://github.com/ros2/rclc/pull/62/commits/0968d2d68326ade6fcbba4ebff64942a8d0c3832)

Also the `ament_export_targets` was not supported in Dashing [commit](https://github.com/ros2/rclc/pull/62/commits/de7e51799dcf8b36255b260bd059869ec7c490d9)

**Comment by pablogs9** [comment]
Is this the final version? let me run it again.

**Comment by JanStaschulat** [comment]
Yes, this would be the final version (build jobs on linux for Dashing, Foxy, Rolling work fine)

**Review by pablogs9 — APPROVED** [review]

**Review by ralph-lange — APPROVED** [review]

**Review by norro — APPROVED** [review]
Very nice, Jan! 
CI not complaining and tried the installation in my Win10 setup as well =>approved! ;)

**Pull request merged**
