### PR TITLE
Foxy backport: windows port and sleep function

### PR DESCRIPTION
**Pull request by JanStaschulat**
@norro 
could you test, if this works on Windows (colcon build, colcon test) with Dashing and Foxy?

### CODE REVIEW

**Review by pablogs9 — APPROVED** [review]

**Comment by JanStaschulat** [comment]
@norro 
I compiled this PR on the Windows PC in the robotics lab with Foxy ROS 2 release. 
the unit tests for rclc run successfully. The unit tests for rclc_lifecycle do not: 

```
[ RUN    ] TestRclcLifecycle.lifecycle_node_transitions
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
[ FAILED ] TestRclcLifecycle.lifecycle_node_transitions (30ms)
...
```
Could you run colcon-test or the binary (ros2_ws\build\rclc_lifecycle\Release\>call rclc_lifecycle_test.exe) on your local Windows installation?

**Comment by norro** [comment]
The `backport-windows-port-and-sleep-func` branch builds and tests without error in my local setup. I tried with `colcon test` and by executing `rclc_lifecycle_test.exe` explicitly.

**Comment by JanStaschulat** [comment]
The build farm CI job was never executed for Dashing. Theferefore I created a new PR https://github.com/ros2/rclc/pull/84

**Comment by JanStaschulat** [comment]
Stale PR, there seems to be a problem with CI build job on Dashing, I created a new PR https://github.com/ros2/rclc/pull/84

**Pull request closed without merging**
