### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by pablogs9**
This PR fix https://github.com/ros2/rclc/issues/127

### CODE REVIEW

**Comment by pablogs9** [comment]
This will be backported to galactic when merged

**Review by JanStaschulat — COMMENTED** [review]
There is also a type in `LENGHT` => `LENGTH`

**Review by JanStaschulat — APPROVED** [review]

**Comment by pablogs9** [comment]
Fixed, merging.

**Comment by pablogs9** [comment]
@mergify backport galactic

**Pull request merged**
