### PR TITLE
package rclc_lifecycle 

### PR DESCRIPTION
**Pull request by JanStaschulat**
New: 
- added rclc_lifecycle package

Updates:
- update maintainer information
- added init_with_options functions

### CODE REVIEW

**Comment by JanStaschulat** [comment]
@pablogs9, @ralph-lange  The unit test with the new function rclc_node_init_with_options() fails for Rolling. 
http://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/2/console#console-section-7

**Comment by pablogs9** [comment]
I'm going to investigate where have they move the domain_id... Definitely, now we should create a foxy branch.

**Comment by JanStaschulat** [comment]
@pablogs9 domain_id  was removed from rcl_node_init and is now set by rcl_init_options_set_domain_id()
https://github.com/ros2/rcl/commit/70eba5e788af95c0e9f0dfe71af9ae630a9d4d76#

**Comment by pablogs9** [comment]
Nice, let me create a foxy branch and include these changes in master in the micro-ROS repos.

**Comment by JanStaschulat** [comment]
@pablogs9 @ralph-lange Hmm, we had also these problems with different ROS 2 versions of rclc for Dashing/Eloqoent/Foxy. If possible I would avoid having multiple branches for ROS 2 releases if possible.. 

For rclc. We solved this by checking the rcl_version number on CMakeList.txt e.g:
https://github.com/ros2/rclc/blob/90873f3cd2fff9b6d23940a0f52ab78521596534/rclc/CMakeLists.txt#L36

if("${rcl_VERSION}" VERSION_LESS "1.0.0")
add_definitions(-DUSE_RCL_WAIT_SET_IS_VALID_BACKPORT)

which will add a MACRO definition, this one is used in th the code
https://github.com/ros2/rclc/blob/90873f3cd2fff9b6d23940a0f52ab78521596534/rclc/src/rclc/executor.c#L26

**Comment by pablogs9** [comment]
Ok Jan, so let's keep just the master branch. I have removed the domain id from this test. We consider that is not necessary for the test purpose.

Please check and approve this: https://github.com/micro-ROS/rclc/pull/48

**Comment by pablogs9** [comment]
Let me check the usage of  `rcl_init_options_set_domain_id()`. If this works I can change the example in micro-ROS demos.

I also prefer Option 2.

**Comment by pablogs9** [comment]
Ok, so `rcl_init_options_set_domain_id()` is not backported to `foxy` branch of RCL. So I'm keeping our examples as their are and when we prepare a Galactic or Rolling release of micro-ROS we will need to use `rcl_init_options_set_domain_id()`.

By now it's ok for us to remove this line from the tests so you don't have problems in this CI.

Let me know if you require any other action from our part.

**Comment by JanStaschulat** [comment]
Hi Pablo, great! That problem is solved.

**Comment by JanStaschulat** [comment]
@ralph-lange @pablogs9 
Hmm, colcon_build and colcon_test works at my local machine for Dashing, Eloquent and Foxy (ros:master I did not test):

jst3si@RNGX5596:~ros2_eloquent$ env | grep DISTRO
ROS_DISTRO=**dashing**
jst3si@RNGX5596:~ros2_eloquent$ colcon test-result
**Summary: 138 tests, 0 errors, 0 failures, 0 skipped**

jst3si@RNGX5596:~ros2_eloquent$ env | grep DISTRO
ROS_DISTRO=**eloquent**
jst3si@RNGX5596:~ros2_eloquent$ colcon test-result
**Summary: 138 tests, 0 errors, 0 failures, 0 skipped**


jst3si@RNGX5596:~ros2_eloquent$ env | grep DISTRO
ROS_DISTRO=**foxy**
jst3si@RNGX5596:~ros2_eloquent$ colcon test-result
**Summary: 138 tests, 0 errors, 0 failures, 0 skipped**

Any ideas how to proceed?

**Comment by pablogs9** [comment]
I think that if we don't have access to this Jenkins server in order to rerun we need to insert a new commit, maybe @jamoralp can tell us something about this.

Regarding the error, I see some warnings during compilation, in some cases, Jenkins can fail on Unstable. Chech [this](https://github.com/micro-ROS/rclc/pull/51#issuecomment-731149127). For example [here](http://build.ros2.org/job/Dpr__rclc__ubuntu_bionic_amd64/9/console) I can't see any error/failed test but the `UNSTABLE` flag due to the compiler warnings.

Regarding the test error, I have no idea. A silly question: are gtest testcases guaranteed to be executed sequentially?

**Comment by ralph-lange** [comment]
@JanStaschulat, instead of ros:master, please include Rolling in your tests. It is installed like the other releases by `sudo apt install ros-rolling-desktop`.

**Comment by ralph-lange** [comment]
Regarding the five failed unit tests ` TestDefaultExecutor.*`: Can you relax the timing requirements to account for the high computational background load on the build farm? It should be strongly avoided that the unit tests fail sporadically due to timing issues. (Your changes will result in another commit, which retriggers the build of the PR.)

**Comment by JanStaschulat** [comment]
@Karsten1987 @norro There is only one compiler warning ...

In file included from /opt/ros/eloquent/include/rcl_lifecycle/rcl_lifecycle.h:25:0,
                 from /home/jst3si/ros2_eloquent/src/rclc/rclc_lifecycle/include/rclc_lifecycle/rclc_lifecycle.h:24,
                 from /home/jst3si/ros2_eloquent/src/rclc/rclc_lifecycle/src/rclc_lifecycle/rclc_lifecycle.c:17:
/opt/ros/eloquent/include/rcl_lifecycle/data_types.h:44:3: warning: redefinition of typedef ‘rcl_lifecycle_transition_t’ [-Wpedantic]
 } rcl_lifecycle_transition_t;
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/eloquent/include/rcl_lifecycle/data_types.h:27:43: note: previous declaration of ‘rcl_lifecycle_transition_t’ was here
 typedef struct rcl_lifecycle_transition_t rcl_lifecycle_transition_t;

which originates from rcl_lifecle/data_types.h In which the struct  ‘rcl_lifecycle_transition_t’ is defined. Any suggestions how to resolve this warning for Dashing and Eloqent? Interestingly, for Foxy there is no error message, however, the structure is defined in the same way:

[CI-Build Error message Dashing](http://build.ros2.org/job/Dpr__rclc__ubuntu_bionic_amd64/9/)
[data_type.h - dashing line 1](https://github.com/ros2/rcl/blob/b05fd81636c24b9ee9e905115b67c5ed829e3fe8/rcl_lifecycle/include/rcl_lifecycle/data_types.h#L38)
[data_type.h - dashing line 2](https://github.com/ros2/rcl/blob/b05fd81636c24b9ee9e905115b67c5ed829e3fe8/rcl_lifecycle/include/rcl_lifecycle/data_types.h#L44)

[CI-Build Error message Eloquent](http://build.ros2.org/job/Epr__rclc__ubuntu_bionic_amd64/9/)
[data_type.h - eloqent line 1](https://github.com/ros2/rcl/blob/df14174f689b164f63ba38bbb2a116e4ded1b325/rcl_lifecycle/include/rcl_lifecycle/data_types.h#L27)
[data_type.h - eloqent line 1](https://github.com/ros2/rcl/blob/df14174f689b164f63ba38bbb2a116e4ded1b325/rcl_lifecycle/include/rcl_lifecycle/data_types.h#L44)


However with the same code, the [CI-build job for Foxy](http://build.ros2.org/job/Fpr__rclc__ubuntu_focal_amd64/4/) has no problems with it:
[data_type.h - foxy line 1](https://github.com/ros2/rcl/blob/df14174f689b164f63ba38bbb2a116e4ded1b325/rcl_lifecycle/include/rcl_lifecycle/data_types.h#L27)
[data_type.h - foxy line 2](https://github.com/ros2/rcl/blob/4376552e7c88a42d3b5d085d11b719f5d8cfd248/rcl_lifecycle/include/rcl_lifecycle/data_types.h#L55)

**Comment by JanStaschulat** [comment]
Created bloom release for
Foxy
ros/rosdistro#27421
Eloquent
ros/rosdistro#27424
Dashing
ros/rosdistro#27425

**Pull request merged**
