### PR TITLE
Add Parameters support to RCLC

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by ralph-lange** [comment]
I reviewed the interface concept as promised. My suggestions:
* Allow fixed-size parameter names only or introduce a mapping from integer constants to strings in the agent as in diagnostics, cf. https://github.com/micro-ROS/micro_ros_diagnostics/issues/5.
* String-type parameters may be omitted initially, i.e. bool, int/long, float/double are enough.
* Also, the parameter client may be omitted in the first PR. I suppose that there are little use-cases for changing parameters of other nodes from an micro-ROS node, but that the 80% case is changing parameters of a micro-ROS node via launch, system-modes, or CLI from standard ROS 2.

**Comment by pablogs9** [comment]
I agree 100% with Ralphs's comments, those are such great ideas for simplifying this implementation.

@FranFin @jamoralp @Acuadros95, if you are ok, maybe we can plan some iterations over this. Thoughts?

**Comment by ralph-lange** [comment]
If you are interested, I may organize a short meeting on the mapping approach used in diagnostics. Perhaps some of the code can be reused.

**Comment by pablogs9** [comment]
In my opinion, the mapping approach should be optional and the micro-ROS client library must be able to work standalone with the restrictions you mention: 
- Fixed-size parameter names
- Not string parameters only
- Implementing only the "parameter server"

**Comment by pablogs9** [comment]
Moving to https://github.com/ros2/rclc/pull/78

**Pull request closed without merging**
