### PR TITLE
Adds service callback with service context 

### PR DESCRIPTION
**Pull request by norro**
Adds an additional callback type and handling that allows passing additional service context (void *) to a service callback.

### CODE REVIEW

**Comment by norro** [comment]
@JanStaschulat The dashing build fails with some python setuptools issue that seems to be an upstream issue.
Do I need to address this in order to get this PR merged?

**Comment by JanStaschulat** [comment]
I have seen that too for my PR. We have to fix that first something with rust ...

**Comment by norro** [comment]
Seems like a problem with either one of the upstream packages or within the setup_ros action.

**Comment by JanStaschulat** [comment]
Problem with dashing release is resolved in https://github.com/micro-ROS/rclc/pull/74
and I created a PR on ros2/rclc https://github.com/ros2/rclc/pull/46

With a 'git pull' the problem should be resolved.

**Review by JanStaschulat — APPROVED** [review]

**Review by JanStaschulat — COMMENTED** [review]
Please resolve unit test error for services and make a pull to resolve Dashing error.

**Review by JanStaschulat — APPROVED** [review]

**Comment by norro** [comment]
@JanStaschulat feel free to merge. I will start working on https://github.com/micro-ROS/rclc/issues/40 afterwards.

**Pull request merged**
