### PR TITLE
Parameters fini memory

### PR DESCRIPTION
**Pull request by pablogs9**
Signed-off-by: Pablo Garrido <pablogs9@gmail.com>

### CODE REVIEW

**Comment by pablogs9** [comment]
Not related error: 
image


We should check

**Comment by JanStaschulat** [comment]
It is related to the PR of the events executor in RMW:
https://github.com/ros2/rclc/issues/254

**Comment by JanStaschulat** [comment]
@pablogs9 the PR https://github.com/ros2/rclc/pull/255 is merged. You can do a rebase. Then the CI Rolling build job should pass.

**Review by JanStaschulat — APPROVED** [review]
LGTM

**Comment by pablogs9** [comment]
@mergify backport galactic

**Comment by pablogs9** [comment]
I have this passing in local and `Rpr__rclc__ubuntu_jammy_amd64` is also ok. Any idea of the timeout in `CI RCLC Rolling / build (ubuntu-20.04, rolling) ` @JanStaschulat ?

**Comment by pablogs9** [comment]
Today's CI is passing, are we ok with that? @JanStaschulat @Acuadros95 can we assume that this is a CI or Action failure?

**Review by JanStaschulat — APPROVED** [review]

**Comment by JanStaschulat** [comment]
I suppose it was an issue at the Github Action. I am fine with merging.

**Pull request merged**
