### PR TITLE
Fix RCLC int parameter get

### PR DESCRIPTION
**Pull request by pablogs9**
PR to fix this in Rolling, then we can discuss the backport to foxy and galactic

### CODE REVIEW

**Review by JanStaschulat — APPROVED** [review]

**Comment by JanStaschulat** [comment]
Hmm:
https://build.ros2.org/job/Gpr__rclc__ubuntu_focal_amd64/173/consoleText
```
ERROR: Branch not suitable for integration as it does not merge cleanly: Command "git merge --ff fd0c9a5d91155d908acd6af893ce9d60bf0d1a0e" returned status code 1:
stdout: CONFLICT (add/add): Merge conflict in rclc_parameter/test/rclc_parameter/test_parameter.cpp
Auto-merging rclc_parameter/test/rclc_parameter/test_parameter.cpp
CONFLICT (add/add): Merge conflict in rclc_parameter/src/rclc_parameter/parameter_server.c
Auto-merging rclc_parameter/src/rclc_parameter/parameter_server.c
CONFLICT (add/add): Merge conflict in rclc_parameter/package.xml
Auto-merging rclc_parameter/package.xml
CONFLICT (add/add): Merge conflict in rclc_parameter/include/rclc_parameter/rclc_parameter.h
Auto-merging rclc_parameter/include/rclc_parameter/rclc_parameter.h
CONFLICT (add/add): Merge conflict in rclc_parameter/CHANGELOG.rst
Auto-merging rclc_parameter/CHANGELOG.rst
Auto-merging rclc_lifecycle/test/test_lifecycle.cpp
CONFLICT (content): Merge conflict in rclc_lifecycle/test/test_lifecycle.cpp
Auto-merging rclc_lifecycle/src/rclc_lifecycle/rclc_lifecycle.c
CONFLICT (content): Merge conflict in rclc_lifecycle/src/rclc_lifecycle/rclc_lifecycle.c
Auto-merging rclc_lifecycle/package.xml
CONFLICT (content): Merge conflict in rclc_lifecycle/package.xml
Auto-merging rclc_lifecycle/include/rclc_lifecycle/rclc_lifecycle.h
CONFLICT (content): Merge conflict in rclc_lifecycle/include/rclc_lifecycle/rclc_lifecycle.h
Auto-merging rclc_lifecycle/README.md
CONFLICT (content): Merge conflict in rclc_lifecycle/README.md
Auto-merging rclc_lifecycle/CHANGELOG.rst
CONFLICT (content): Merge conflict in rclc_lifecycle/CHANGELOG.rst
Auto-merging rclc_examples/src/example_service_node.c
CONFLICT (add/add): Merge conflict in rclc_examples/src/example_pingpong_helper.h
Auto-merging rclc_examples/src/example_pingpong_helper.h
CONFLICT (add/add): Merge conflict in rclc_examples/src/example_pingpong_helper.c
Auto-merging rclc_examples/src/example_pingpong_helper.c
CONFLICT (add/add): Merge conflict in rclc_examples/src/example_pingpong.cpp
Auto-merging rclc_examples/src/example_pingpong.cpp
CONFLICT (add/add): Merge conflict in rclc_examples/src/example_parameter_server.c
Auto-merging rclc_examples/src/example_parameter_server.c
Auto-merging rclc_examples/src/example_lifecycle_node.c
CONFLICT (content): Merge conflict in rclc_examples/src/example_lifecycle_node.c
Auto-merging rclc_examples/src/example_executor_convenience.c
Auto-merging rclc_examples/src/example_executor.c
Auto-merging rclc_examples/src/example_client_node.c
Auto-merging rclc_examples/package.xml
CONFLICT (content): Merge conflict in rclc_examples/package.xml
Auto-merging rclc_examples/CMakeLists.txt
CONFLICT (content): Merge conflict in rclc_examples/CMakeLists.txt
Auto-merging rclc_examples/CHANGELOG.rst
CONFLICT (content): Merge conflict in rclc_examples/CHANGELOG.rst
Auto-merging rclc/src/rclc/init.c
CONFLICT (content): Merge conflict in rclc/src/rclc/init.c
Auto-merging rclc/src/rclc/executor.c
CONFLICT (content): Merge conflict in rclc/src/rclc/executor.c
Auto-merging rclc/package.xml
CONFLICT (content): Merge conflict in rclc/package.xml
Auto-merging rclc/include/rclc/executor_handle.h
CONFLICT (content): Merge conflict in rclc/include/rclc/executor_handle.h
Auto-merging rclc/include/rclc/executor.h
Auto-merging rclc/README.md
CONFLICT (content): Merge conflict in rclc/README.md
Auto-merging rclc/CMakeLists.txt
Auto-merging rclc/CHANGELOG.rst
Auto-merging dependencies.repos
CONFLICT (content): Merge conflict in dependencies.repos
Auto-merging README.md
Auto-merging .github/workflows/ci.yml
CONFLICT (content): Merge conflict in .github/workflows/ci.yml
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by pablogs9** [comment]
The CI made a mess with the two PR... maybe bc the same name?

**Comment by JanStaschulat** [comment]
tried again with `git cherry-pick fd0c9a5d91155d908acd6af893ce9d60bf0d1a0e`
https://github.com/ros2/rclc/pull/272

**Comment by pablogs9** [comment]
Can we close this in favor of https://github.com/ros2/rclc/pull/272 ?

**Pull request closed without merging**
