### PR TITLE
Revert "Revert "Decouple rosout publisher init from node init. (#351)…

### PR DESCRIPTION
**Pull request by fujitatomoya**
…" (#352)"

This reverts commit 2648503e3fdcf1308bd1d3748e1f4792285cd1b1.

depends on ros2/rcl#1065 (please keep this open until ros2/rcl#1065 is merged.)

address ros2/rclcpp#2147

### CODE REVIEW

**Review by iuhilnehc-ynos — APPROVED** [review]

**Comment by fujitatomoya** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18984/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13508/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19728/)

**Comment by JanStaschulat** [comment]
The [failed test cases of the Linux CI job](https://ci.ros2.org/job/ci_linux/18984/#showFailuresLink) seem not to relate to rclc?

**Comment by fujitatomoya** [comment]
@JanStaschulat thanks for checking on this.

all related PRs are almost ready, I will let you know once https://github.com/ros2/rcl/pull/1065#issuecomment-1598084150 goes green.

**Comment by fujitatomoya** [comment]
CI(rclc for Linux): all green
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18995/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13519/)

**Comment by fujitatomoya** [comment]
I will go ahead to close this one, and reopen targeted to rolling branch.

**Pull request closed without merging**
