### PR TITLE
Create service context in main

### PR DESCRIPTION
**Pull request by norro**
Context passed to the lifecycle services needs to be created in main.

Fixes https://github.com/ros2/rclc/issues/223

Signed-off-by: Nordmann Arne (CR/ADT3) <arne.nordmann@de.bosch.com>

### CODE REVIEW

**Comment by JanStaschulat** [comment]
`lifecycle_node` was also created in main:
https://github.com/ros2/rclc/blob/27b4d4fc30149339da50376acd08893141748aa5/rclc_examples/src/example_lifecycle_node.c#L86
why does this work with `context`?

**Review by JanStaschulat — COMMENTED** [review]
Fine for me, but I don't see why this fixes the problem, as the lifecycle_node was also created in main function 

https://github.com/ros2/rclc/blob/27b4d4fc30149339da50376acd08893141748aa5/rclc_examples/src/example_lifecycle_node.c#L86

**Comment by JanStaschulat** [comment]
Error on buid farm is unclear:
https://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/333/gcc/

the lines reported don't have a return value!?

**Review by JanStaschulat — APPROVED** [review]

**Comment by JanStaschulat** [comment]
no backport to Galactic, Foxy possible due to API break in
`rclc_lifecycle_init_get_state_server()`, `rclc_lifecycle_init_get_available_states_server()` and `rclc_lifecycle_init_change_state_server()`.

**Comment by JanStaschulat** [comment]
@norro could you add a note in the header file for Galactic and Foxy, that lifecycle with context does not work for Galactic and Foxy but that the the issue was fixed in Rolling?

**Comment by norro** [comment]
Yes, I will do.

**Pull request merged**
