### PR TITLE
added dependency for package performance-test-fixture

### PR DESCRIPTION
**Pull request by JanStaschulat**
failing CI build in rclc on rolling: first failing build on https://github.com/ros2/rclc/runs/5136827515?check_suite_focus=true
resolves issue https://github.com/ros2/rclc/issues/246

CC: @norro

### CODE REVIEW

**Comment by JanStaschulat** [comment]
@pablogs9 @ralph-lange  @norro 

When attempting to download the missing dependency, user interaction is required and then the CI job stops. 
Any ideas, how to solve this?
```
 The following NEW packages will be installed:
  libbenchmark-dev libbenchmark1 ros-rolling-ament-cmake-google-benchmark
  ros-rolling-google-benchmark-vendor ros-rolling-performance-test-fixture
0 upgraded, 5 newly installed, 0 to remove and 6 not upgraded.
Need to get 313 kB of archives.
After this operation, 1,122 kB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
Error: Process completed with exit code 1.
```

https://github.com/ros2/rclc/runs/5229443757?check_suite_focus=true

**Comment by pablogs9** [comment]
Maybe `apt-get -y install [package]`? The `-y` assumes yes to all user inputs. Also you have `export DEBIAN_FRONTEND=noninteractive`, check [here](https://askubuntu.com/questions/972516/debian-frontend-environment-variable)

**Review by pablogs9 — APPROVED** [review]

**Comment by norro** [comment]
`apt-get -y` in teh CI file should do the trick (`-y` meaning "answer yes to everything")

**Comment by JanStaschulat** [comment]
Most most recent version of [ros-tooling/action-ros-ci 0.2.3](https://github.com/ros-tooling/action-ros-ci/releases/tag/0.2.3) changed exactly that to "noninteractive" mode. https://github.com/ros-tooling/action-ros-ci/pull/701

**Comment by JanStaschulat** [comment]
Now the library [ros2/mimick](https://github.com/ros2/mimick) is missing.
```
   In file included from /__w/rclc/rclc/ros_ws/src/rcl/rcl_yaml_param_parser/test/test_parse.cpp:28:
  /__w/rclc/rclc/ros_ws/src/rcl/rcl_yaml_param_parser/test/./mocking_utils/patch.hpp:38:10: fatal error: mimick/mimick.h: No such file or directory
     38 | #include "mimick/mimick.h"
```
https://github.com/ros2/rclc/runs/5229849183?check_suite_focus=true

But I can't install it as usual with `apt-get install ros-rolling-mimick`
```
E: Unable to locate package ros-rolling-mimick
Error: Process completed with exit code 100.
```
https://github.com/ros2/rclc/runs/5230169797?check_suite_focus=true

**Pull request merged**
