### PR TITLE
rclc_executor: improve enum type names

### PR DESCRIPTION
**Pull request by JanStaschulat**
see issue https://github.com/ros2/rclc/issues/378

Thanks for your suggestion to improve the names of the enum type names @gavanderhoorn.

### CODE REVIEW

**Comment by JanStaschulat** [comment]
@mergifyio backport iron humble

**Comment by gavanderhoorn** [comment]
Thanks for addressing #378.

Tiny suggestion: I've seen other maintainers use a common prefix for `enum` members. This helps discoverability, especially when using an editor with code-completion (ie: start typing `PREFIX_` and all values show up).

Using a prefix instead of an `_EXECUTOR` suffix would align with that practice, but it's completely up to you.

**Review by pablogs9 — APPROVED** [review]
Just a comment, what about prefixing them with `RCLC_***` ?

**Review by gavanderhoorn — APPROVED** [review]
👍

**Comment by gavanderhoorn** [comment]
Thank you @JanStaschulat 👍

**Pull request merged**
